version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
        # volumes:
        #- ./frontend:/app
        #- /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - AI_PROCESSOR_URL=http://ai-processor:5001
      - DATABASE_PATH=./database/lca.db
    depends_on:
      - ai-processor
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/database:/app/database

  ai-processor:
    build:
      context: ./ai-processor
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - AI_PORT=5001
      - DEBUG=False
      - FLASK_ENV=development
    volumes:
      - ./ai-processor:/app

volumes:
  db_data: